[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
tokio = { version = "1.44.1", features = ["full"] }
futures-util = "0.3.31"
url = "2.5.4"
